Android changes
BrightcovePS/dabble-react-native-brightcove-player pull request #4
Opened 2023-10-16 18:30 UTC by Kanchan-Salotra-brightcove

Geo restriction changes applied .
![image](https://github.com/BrightcovePS/dabble-react-native-brightcove-player/assets/144018139/04576c82-9da7-4dd1-9303-124b8d8e25ff)

2023-10-17 18:21 UTC, backer reviewed
this looks good to me but waiting on our test account to be updated with playback rights so that we can verify

2023-10-18 22:40 UTC, backer commented on example/android/app/src/main/java/com/example/MainActivity.java
> +  protected void onCreate(Bundle savedInstanceState) {
for PiP, let's create a `BrightcoveReactActivity` that extends `ReactActivity` and includes the necessary callbacks to support PiP. Then the `example/MainActivity` can extend that in order to support it in the react native application

2023-10-20 17:47 UTC, backer commented
@Kanchan-Salotra-brightcove when using png's for image resources, we need to include versions in each image set (mdpi through xxhdpi). Also, I see that you have been force-pushing to this branch, which erases the commit history for it each time. Please push normally moving forward, thanks!

2023-10-25 14:16 UTC, Kanchan-Salotra-brightcove commented
@backer ,
all the png icons are added ,Please check.

2023-10-25 19:12 UTC, backer commented
@Kanchan-Salotra-brightcove I tried pulling and running to check the PiP behavior but I'm running into build errors. Have you dev tested to confirm that everything is working properly?

2023-10-26 12:58 UTC, Kanchan-Salotra-brightcove commented
hi @backer , 

Yes i have rechecked all is working fine. as per the expectation.

2023-10-26 20:28 UTC, backer requested changes
looking over the image assets, we shouldn't be using a chevron for the PiP button. I recommend using the ootb player button ui even if we use custom click/visibility logic. Alternatively, we could use an image more representative of PiP, like the attached SVG.

![Vector (1)](https://github.com/BrightcovePS/dabble-react-native-brightcove-player/assets/19782241/3e1243e8-8c70-44d6-ae20-a572681e741b)

2023-10-27 21:00 UTC, backer approved these changes
👍

2023-10-28 11:08 UTC, merged